version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hw2_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: hw2_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: python main.py

volumes:
  postgres_data:
